// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClyhuza4lTJhV8tJAO94aL6MrMXSKNu1g',
    appId: '1:575103717035:web:1d455379ec8468d6ef31ee',
    messagingSenderId: '575103717035',
    projectId: 'logs-3e873',
    authDomain: 'logs-3e873.firebaseapp.com',
    storageBucket: 'logs-3e873.appspot.com',
    measurementId: 'G-K5LFJW06RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3s66DRovJojPm3owHj4-9SrOrv9AOgw',
    appId: '1:575103717035:android:925f0f890dca3838ef31ee',
    messagingSenderId: '575103717035',
    projectId: 'logs-3e873',
    storageBucket: 'logs-3e873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAavZtbXD84BC7WC4eQDhAx5o1WO_wrhmA',
    appId: '1:575103717035:ios:472b5b462de32560ef31ee',
    messagingSenderId: '575103717035',
    projectId: 'logs-3e873',
    storageBucket: 'logs-3e873.appspot.com',
    iosBundleId: 'com.example.diseaseBreakoutAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAavZtbXD84BC7WC4eQDhAx5o1WO_wrhmA',
    appId: '1:575103717035:ios:472b5b462de32560ef31ee',
    messagingSenderId: '575103717035',
    projectId: 'logs-3e873',
    storageBucket: 'logs-3e873.appspot.com',
    iosBundleId: 'com.example.diseaseBreakoutAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClyhuza4lTJhV8tJAO94aL6MrMXSKNu1g',
    appId: '1:575103717035:web:22c79ccb0a5260acef31ee',
    messagingSenderId: '575103717035',
    projectId: 'logs-3e873',
    authDomain: 'logs-3e873.firebaseapp.com',
    storageBucket: 'logs-3e873.appspot.com',
    measurementId: 'G-4EHQDJNKKB',
  );

}